### ISSUE TITLE
Installation issue on raspbian buster

### ISSUE THREAD

**Issue by maciejs1982** [amboxer21/SSHMonitor#30]
OSError: /root/scripts/SSHMonitor/src/lib/shared/libbuild.so: wrong ELF class: ELFCLASS64

**Comment by amboxer21** [comment]
Are you using a 32bit system? Have you tried rebuilding libbuild.so ? Read [THIS](https://github.com/amboxer21/SSHMonitor/blob/master/README) internal readme.

```
Building libbuild.so
gcc -c -fPIC src/build.c -o libbuild.o
gcc libbuild.o -shared -o libbuild.so
cp -i src/lib/shared/libbuild.so src/lib/shared/original.libbuild.so
cp libbuild.so src/lib/shared/
```

**Comment by maciejs1982** [comment]
Thanks, that helps. Should have red all info 1st.
